project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

book:
  title: "Analysis of Power and Thermal Behavior in HPC Supercomputers"
  author:
    - Vara Tummala (vjt2110)
  repo-url: https://github.com/varat01/Analysis-of-Power-and-Thermal-Behavior-in-HPC-Supercomputers
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true
